name: Build for iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Xamarin.iOS
        run: brew install --cask xamarin-ios

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies with dotnet restore
        run: dotnet restore

      - name: Restore dependencies with nuget restore
        run: nuget restore

      - name: Create GoogleService-Info.plist file
        run: 'echo "$GOOGLE_SERVICE__INFO_PLIST" > Vulcanova/Vulcanova.iOS/GoogleService-Info.plist'
        env:
          GOOGLE_SERVICE__INFO_PLIST: ${{ secrets.GOOGLE_SERVICE__INFO_PLIST }}

      - name: Build NativeCompanion
        run: xcodebuild -project NativeCompanion/NativeCompanion.xcodeproj -scheme NativeWidgetExtension -sdk iphoneos -arch arm64 -derivedDataPath NativeCompanion/DerivedData/NativeCompanion -configuration Release build CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""

      - name: Build
        run: /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono '/Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/MSBuild.dll'  Vulcanova/Vulcanova.iOS/Vulcanova.iOS.csproj /p:Configuration='Release' /t:Build /p:Platform='iPhone' /p:BuildIpa=true /p:EnableCodeSigning=false

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: Vulcanova/Vulcanova.iOS/bin/iPhone/Release/Vulcanova.iOS.ipa
